# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5 # Use the latest appropriate version
    hooks:
      - id: insert-license
        name: Insert license headers (#-style comments)
        args:
          - "--license-filepath"
          - "LICENSE_HEADER.md"
          - "--comment-style"
          - "#"
        files: ^(Justfile|justfile)$|\\.(yaml|yml|py|sh|Dockerfile.*|rb|pl|ex|exs)$
        exclude: ^(thirdparty/|deps/|_build/|LICENSE\.md$|LICENSE_HEADER\.txt$|.*\.md$|\.gitignore|\.gitattributes|\.tool-versions|.*\.json|.*\.html|.*\.css|.*\.js)

      - id: insert-license
        name: Insert license headers (//-style comments for C++)
        args:
          - "--license-filepath"
          - "LICENSE_HEADER.md"
          - "--comment-style"
          - "//"
        files: \.(cpp|hpp|h|cc|cxx|c)$
        exclude: ^(thirdparty/|deps/|_build/|LICENSE\.md$|LICENSE_HEADER\.txt$|.*\.md$|\.gitignore|\.gitattributes|\.tool-versions|.*\.json|.*\.html|.*\.css|.*\.js)
      - id: forbid-crlf  # Forbid files containing CRLF end-lines to be committed
      - id: remove-crlf  # Replace CRLF end-lines by LF ones before committing