# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

version: '3.8'

services:
  softhsm-setup:
    build:
      context: ./docker_softhsm
      dockerfile: Dockerfile
    environment:
      - OPENBAO_PKCS11_PIN=${OPENBAO_PKCS11_PIN:-1234}
      - OPENBAO_PKCS11_SO_PIN=${OPENBAO_PKCS11_SO_PIN:-5678}
      - OPENBAO_PKCS11_SLOT=${OPENBAO_PKCS11_SLOT:-0}
    volumes:
      - softhsm_tokens:/var/lib/softhsm/tokens
    # This is a one-time setup service, not a long-running service
    restart: "no"

  openbao:
    build:
      context: ./docker_openbao
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - BAO_DEV_ROOT_TOKEN_ID=root
      - BAO_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - OPENBAO_PKCS11_PIN=${OPENBAO_PKCS11_PIN:-1234}
      - OPENBAO_PKCS11_SO_PIN=${OPENBAO_PKCS11_SO_PIN:-5678}
      - OPENBAO_PKCS11_SLOT=${OPENBAO_PKCS11_SLOT:-0}
    volumes:
      - openbao_data:/vault/data
      - softhsm_tokens:/var/lib/softhsm/tokens:ro
    command: ["bao", "server", "-dev", "-dev-listen-address=0.0.0.0:8200"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - softhsm-setup

  cockroachdb:
    image: v-sekai/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure", "--host=localhost:26257"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  openbao_data:
  softhsm_tokens:
  cockroachdb_data:
