# Fly.io Database Configuration
# CockroachDB cluster for Aria Character Core

app = "aria-character-core-db"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.cockroachdb"

[deploy]
  strategy = "immediate"

[env]
  COCKROACH_DATABASE = "aria_data_prod"
  COCKROACH_USER = "aria_user"
  COCKROACH_CERTS_DIR = "/cockroach/certs"

[[mounts]]
  source = "cockroach_data"
  destination = "/cockroach/cockroach-data"

[[services]]
  processes = ["db"]
  internal_port = 26257
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 26257
    handlers = ["pg_tls"]

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"

[[services]]
  processes = ["db"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080
    handlers = ["http"]

  [[services.http_checks]]
    interval = "30s"
    grace_period = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = "10s"

[processes]
  db = "/usr/local/bin/start-cockroach.sh"

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 4
