# Fly.io OpenBao Configuration  
# Secrets management for Aria Character Core

app = "aria-character-core-vault"
primary_region = "ord"

[build]
  image = "openbao/openbao:2.2.2"

[deploy]
  strategy = "immediate"

[env]
  OPENBAO_DEV_ROOT_TOKEN_ID = "aria-dev-token"
  OPENBAO_DEV_LISTEN_ADDRESS = "0.0.0.0:8200"
  SOFTHSM2_CONF = "/etc/softhsm2.conf"

[[mounts]]
  source = "vault_data"
  destination = "/vault/data"

[[services]]
  processes = ["vault"]
  internal_port = 8200
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 8200
    handlers = ["http"]

  [[services.http_checks]]
    interval = "30s"
    grace_period = "30s"
    method = "GET"
    path = "/v1/sys/health"
    protocol = "http"
    restart_limit = 0
    timeout = "10s"

[processes]
  vault = "sh -c 'apk add --no-cache softhsm && mkdir -p /etc/softhsm /vault/data/tokens && echo \"directories.tokendir = /vault/data/tokens\" > /etc/softhsm2.conf && echo \"objectstore.backend = file\" >> /etc/softhsm2.conf && echo \"log.level = INFO\" >> /etc/softhsm2.conf && softhsm2-util --init-token --slot 0 --label \"aria-token\" --pin 1234 --so-pin 1234 2>/dev/null || true && bao server -dev -dev-root-token-id=aria-dev-token -dev-listen-address=0.0.0.0:8200'"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
