# Aria Character Core - Main Application
# Fly.io configuration for the umbrella application

app = "aria-character-core"
primary_region = "ord"

[build]
  builder = "hexpm/elixir:1.16.3-erlang-26.2.5-alpine-3.19.1"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "aria-character-core.fly.dev"
  PORT = "4000"
  MIX_ENV = "prod"
  ERL_AFLAGS = "-proto_dist inet6_tcp"

[experimental]
  auto_rollback = true

[[mounts]]
  source = "aria_data"
  destination = "/app/data"

[[services]]
  internal_port = 8200
  protocol = "tcp"

  [[services.ports]]
    port = 8200
    handlers = ["tcp"]
[processes]
  app = "mix phx.server"
