defmodule AriaEngine.Pddl.DomainAdapter do
  @moduledoc """
  Adapts an `AriaEngine.Pddl.Domain` struct to conform to the `AriaEngine.DomainBehaviour`.
  This allows `AriaEngine.Plan` to work with PDDL domains.
  """
  use AriaEngine.DomainBehaviour

  alias AriaEngine.Pddl.Domain
  alias AriaEngine.Pddl.Domain.{Action, Method} # Alias for PDDL-specific structs

  @doc """
  Returns the actions from the PDDL domain.
  """
  @impl true
  def actions(%Domain{actions: pddl_actions}) do
    # PDDL actions are data structures, not executable functions directly.
    # For now, return placeholder functions. The actual action functions
    # would be generated by a PDDL interpreter/compiler.
    Enum.reduce(pddl_actions, %{}, fn %Action{name: name}, acc ->
      Map.put(acc, name, fn _state, _args -> {:error, "Action not implemented: #{name}"} end)
    end)
  end

  @doc """
  Returns the task methods from the PDDL domain.
  """
  @impl true
  def task_methods(%Domain{methods: pddl_methods}) do
    # PDDL methods are data structures, not executable functions directly.
    # For now, return placeholder functions. The actual method functions
    # would be generated by a PDDL interpreter/compiler.
    Enum.reduce(pddl_methods, %{}, fn %Method{task: task, name: method_name}, acc ->
      task_name = Atom.to_string(task)
      named_method = {method_name, fn _state, _args -> {:error, "Method not implemented: #{method_name}"} end}
      Map.update(acc, task_name, [named_method], fn existing_methods ->
        existing_methods ++ [named_method]
      end)
    end)
  end

  @doc """
  Returns the unigoal methods from the PDDL domain.
  """
  @impl true
  def unigoal_methods(%Domain{methods: _methods}) do
    # Assuming unigoal methods are also part of the general 'methods' list
    # and can be identified by a specific task name pattern or metadata.
    # For now, we'll return an empty map as PDDL doesn't have a direct "unigoal" concept.
    # This will need to be refined when PDDL parsing for goals is more explicit.
    %{}
  end

  @doc """
  Returns the multigoal methods from the PDDL domain.
  """
  @impl true
  def multigoal_methods(%Domain{methods: _methods}) do
    # Similar to unigoal methods, PDDL doesn't have a direct "multigoal" concept.
    # Returning an empty list for now.
    []
  end

  # Placeholder implementations for durative versions
  @impl true
  def durative_actions(_domain), do: %{}
  @impl true
  def durative_task_methods(_domain), do: %{}
  @impl true
  def durative_unigoal_methods(_domain), do: %{}
  @impl true
  def durative_multigoal_methods(_domain), do: []

  @doc """
  Converts an `AriaEngine.Pddl.Domain` struct to an `AriaEngine.Domain` struct.
  This is a temporary conversion for compatibility with `AriaEngine.Plan`.
  """
  @spec to_aria_engine_domain(Domain.t()) :: AriaEngine.Domain.t()
  def to_aria_engine_domain(%Domain{} = pddl_domain) do
    %AriaEngine.Domain{
      name: Atom.to_string(pddl_domain.name),
      actions: actions(pddl_domain),
      task_methods: task_methods(pddl_domain),
      unigoal_methods: unigoal_methods(pddl_domain),
      multigoal_methods: multigoal_methods(pddl_domain)
      # Note: action_metadata is not directly available in PDDL.Domain
      # and will be empty for now.
    }
  end
end
