defmodule AriaEngine.GltfKhrInteractivity.PlanningTest do
  use ExUnit.Case, async: true

  alias AriaEngine.StateV2
  alias AriaEngine.Planning

  test "plan the development of the glTF KHR Interactivity extension" do
    initial_state =
      StateV2.new()
      # Phase 1: Core Data Structures
      |> StateV2.set_fact("gltf_scene", "type", "module")
      |> StateV2.set_fact("gltf_node", "type", "module")
      |> StateV2.set_fact("gltf_mesh", "type", "module")
      |> StateV2.set_fact("gltf_mesh_primitive", "type", "module")
      |> StateV2.set_fact("gltf_accessor", "type", "module")
      |> StateV2.set_fact("gltf_buffer", "type", "module")
      |> StateV2.set_fact("gltf_buffer_view", "type", "module")
      |> StateV2.set_fact("gltf_material", "type", "module")
      |> StateV2.set_fact("gltf_texture", "type", "module")
      |> StateV2.set_fact("gltf_image", "type", "module")
      |> StateV2.set_fact("gltf_sampler", "type", "module")
      |> StateV2.set_fact("gltf_animation", "type", "module")
      |> StateV2.set_fact("gltf_animation_channel", "type", "module")
      |> StateV2.set_fact("gltf_animation_sampler", "type", "module")
      |> StateV2.set_fact("gltf_camera", "type", "module")
      |> StateV2.set_fact("gltf_skin", "type", "module")

      # Phase 2: Data Loading & Parsing
      |> StateV2.set_fact("gltf_loader", "type", "module")
      |> StateV2.set_fact("gltf_accessor_view", "type", "module")

      # Phase 3: Scene Graph Logic
      |> StateV2.set_fact("gltf_scene_graph", "type", "module")

      # Phase 4: Mesh and Primitive Processing
      |> StateV2.set_fact("gltf_mesh_processing", "type", "module")

      # Dependencies
      |> StateV2.set_fact("gltf_node", "depends_on", "gltf_scene")
      |> StateV2.set_fact("gltf_mesh", "depends_on", "gltf_node")
      |> StateV2.set_fact("gltf_mesh_primitive", "depends_on", "gltf_mesh")
      |> StateV2.set_fact("gltf_accessor", "depends_on", "gltf_buffer_view")
      |> StateV2.set_fact("gltf_buffer_view", "depends_on", "gltf_buffer")
      |> StateV2.set_fact("gltf_material", "depends_on", "gltf_texture")
      |> StateV2.set_fact("gltf_texture", "depends_on", "gltf_image")
      |> StateV2.set_fact("gltf_texture", "depends_on", "gltf_sampler")
      |> StateV2.set_fact("gltf_animation", "depends_on", "gltf_animation_channel")
      |> StateV2.set_fact("gltf_animation", "depends_on", "gltf_animation_sampler")
      |> StateV2.set_fact("gltf_skin", "depends_on", "gltf_node")
      |> StateV2.set_fact("gltf_loader", "depends_on", "gltf_accessor")
      |> StateV2.set_fact("gltf_accessor_view", "depends_on", "gltf_accessor")
      |> StateV2.set_fact("gltf_scene_graph", "depends_on", "gltf_node")
      |> StateV2.set_fact("gltf_mesh_processing", "depends_on", "gltf_mesh_primitive")
      |> StateV2.set_fact("gltf_mesh_processing", "depends_on", "gltf_accessor_view")

      # KHR Interactivity Nodes - Math
      |> StateV2.set_fact("khr_math_e", "type", "module")
      |> StateV2.set_fact("khr_math_pi", "type", "module")
      |> StateV2.set_fact("khr_math_infinity", "type", "module")
      |> StateV2.set_fact("khr_math_nan", "type", "module")
      |> StateV2.set_fact("khr_math_abs", "type", "module")
      |> StateV2.set_fact("khr_math_sign", "type", "module")
      |> StateV2.set_fact("khr_math_trunc", "type", "module")
      |> StateV2.set_fact("khr_math_floor", "type", "module")
      |> StateV2.set_fact("khr_math_ceil", "type", "module")
      |> StateV2.set_fact("khr_math_round", "type", "module")
      |> StateV2.set_fact("khr_math_fract", "type", "module")
      |> StateV2.set_fact("khr_math_neg", "type", "module")
      |> StateV2.set_fact("khr_math_add", "type", "module")
      |> StateV2.set_fact("khr_math_sub", "type", "module")
      |> StateV2.set_fact("khr_math_mul", "type", "module")
      |> StateV2.set_fact("khr_math_div", "type", "module")
      |> StateV2.set_fact("khr_math_rem", "type", "module")
      |> StateV2.set_fact("khr_math_min", "type", "module")
      |> StateV2.set_fact("khr_math_max", "type", "module")
      |> StateV2.set_fact("khr_math_clamp", "type", "module")
      |> StateV2.set_fact("khr_math_saturate", "type", "module")
      |> StateV2.set_fact("khr_math_mix", "type", "module")

      # KHR Interactivity Nodes - Comparison
      |> StateV2.set_fact("khr_math_eq", "type", "module")
      |> StateV2.set_fact("khr_math_lt", "type", "module")
      |> StateV2.set_fact("khr_math_le", "type", "module")
      |> StateV2.set_fact("khr_math_gt", "type", "module")
      |> StateV2.set_fact("khr_math_ge", "type", "module")

      # KHR Interactivity Nodes - Special
      |> StateV2.set_fact("khr_math_is_nan", "type", "module")
      |> StateV2.set_fact("khr_math_is_inf", "type", "module")
      |> StateV2.set_fact("khr_math_select", "type", "module")
      |> StateV2.set_fact("khr_math_switch", "type", "module")
      |> StateV2.set_fact("khr_math_random", "type", "module")

      # KHR Interactivity Nodes - Angle/Trigonometry
      |> StateV2.set_fact("khr_math_rad", "type", "module")
      |> StateV2.set_fact("khr_math_deg", "type", "module")
      |> StateV2.set_fact("khr_math_sin", "type", "module")
      |> StateV2.set_fact("khr_math_cos", "type", "module")
      |> StateV2.set_fact("khr_math_tan", "type", "module")
      |> StateV2.set_fact("khr_math_asin", "type", "module")
      |> StateV2.set_fact("khr_math_acos", "type", "module")
      |> StateV2.set_fact("khr_math_atan", "type", "module")
      |> StateV2.set_fact("khr_math_atan2", "type", "module")

      # KHR Interactivity Nodes - Hyperbolic
      |> StateV2.set_fact("khr_math_sinh", "type", "module")
      |> StateV2.set_fact("khr_math_cosh", "type", "module")
      |> StateV2.set_fact("khr_math_tanh", "type", "module")
      |> StateV2.set_fact("khr_math_asinh", "type", "module")
      |> StateV2.set_fact("khr_math_acosh", "type", "module")
      |> StateV2.set_fact("khr_math_atanh", "type", "module")

      # KHR Interactivity Nodes - Exponential
      |> StateV2.set_fact("khr_math_exp", "type", "module")
      |> StateV2.set_fact("khr_math_log", "type", "module")
      |> StateV2.set_fact("khr_math_log2", "type", "module")
      |> StateV2.set_fact("khr_math_log10", "type", "module")
      |> StateV2.set_fact("khr_math_sqrt", "type", "module")
      |> StateV2.set_fact("khr_math_cbrt", "type", "module")
      |> StateV2.set_fact("khr_math_pow", "type", "module")

      # KHR Interactivity Nodes - Vector
      |> StateV2.set_fact("khr_math_length", "type", "module")
      |> StateV2.set_fact("khr_math_normalize", "type", "module")
      |> StateV2.set_fact("khr_math_dot", "type", "module")
      |> StateV2.set_fact("khr_math_cross", "type", "module")
      |> StateV2.set_fact("khr_math_rotate2d", "type", "module")
      |> StateV2.set_fact("khr_math_rotate3d", "type", "module")
      |> StateV2.set_fact("khr_math_transform", "type", "module")

      # KHR Interactivity Nodes - Matrix
      |> StateV2.set_fact("khr_math_transpose", "type", "module")
      |> StateV2.set_fact("khr_math_determinant", "type", "module")
      |> StateV2.set_fact("khr_math_inverse", "type", "module")
      |> StateV2.set_fact("khr_math_matmul", "type", "module")
      |> StateV2.set_fact("khr_math_matcompose", "type", "module")
      |> StateV2.set_fact("khr_math_matdecompose", "type", "module")

      # KHR Interactivity Nodes - Quaternion
      |> StateV2.set_fact("khr_math_quat_conjugate", "type", "module")
      |> StateV2.set_fact("khr_math_quat_mul", "type", "module")
      |> StateV2.set_fact("khr_math_quat_angle_between", "type", "module")
      |> StateV2.set_fact("khr_math_quat_from_axis_angle", "type", "module")
      |> StateV2.set_fact("khr_math_quat_to_axis_angle", "type", "module")
      |> StateV2.set_fact("khr_math_quat_from_directions", "type", "module")

      # KHR Interactivity Nodes - Swizzle
      |> StateV2.set_fact("khr_math_combine2", "type", "module")
      |> StateV2.set_fact("khr_math_combine3", "type", "module")
      |> StateV2.set_fact("khr_math_combine4", "type", "module")
      |> StateV2.set_fact("khr_math_combine2x2", "type", "module")
      |> StateV2.set_fact("khr_math_combine3x3", "type", "module")
      |> StateV2.set_fact("khr_math_combine4x4", "type", "module")
      |> StateV2.set_fact("khr_math_extract2", "type", "module")
      |> StateV2.set_fact("khr_math_extract3", "type", "module")
      |> StateV2.set_fact("khr_math_extract4", "type", "module")
      |> StateV2.set_fact("khr_math_extract2x2", "type", "module")
      |> StateV2.set_fact("khr_math_extract3x3", "type", "module")
      |> StateV2.set_fact("khr_math_extract4x4", "type", "module")

      # KHR Interactivity Nodes - Integer Arithmetic
      |> StateV2.set_fact("khr_int_abs", "type", "module")
      |> StateV2.set_fact("khr_int_sign", "type", "module")
      |> StateV2.set_fact("khr_int_neg", "type", "module")
      |> StateV2.set_fact("khr_int_add", "type", "module")
      |> StateV2.set_fact("khr_int_sub", "type", "module")
      |> StateV2.set_fact("khr_int_mul", "type", "module")
      |> StateV2.set_fact("khr_int_div", "type", "module")
      |> StateV2.set_fact("khr_int_rem", "type", "module")
      |> StateV2.set_fact("khr_int_min", "type", "module")
      |> StateV2.set_fact("khr_int_max", "type", "module")
      |> StateV2.set_fact("khr_int_clamp", "type", "module")

      # KHR Interactivity Nodes - Integer Comparison
      |> StateV2.set_fact("khr_int_eq", "type", "module")
      |> StateV2.set_fact("khr_int_lt", "type", "module")
      |> StateV2.set_fact("khr_int_le", "type", "module")
      |> StateV2.set_fact("khr_int_gt", "type", "module")
      |> StateV2.set_fact("khr_int_ge", "type", "module")

      # KHR Interactivity Nodes - Integer Bitwise
      |> StateV2.set_fact("khr_int_not", "type", "module")
      |> StateV2.set_fact("khr_int_and", "type", "module")
      |> StateV2.set_fact("khr_int_or", "type", "module")
      |> StateV2.set_fact("khr_int_xor", "type", "module")
      |> StateV2.set_fact("khr_int_asr", "type", "module")
      |> StateV2.set_fact("khr_int_lsl", "type", "module")
      |> StateV2.set_fact("khr_int_clz", "type", "module")
      |> StateV2.set_fact("khr_int_ctz", "type", "module")
      |> StateV2.set_fact("khr_int_popcnt", "type", "module")

      # KHR Interactivity Nodes - Boolean Arithmetic
      |> StateV2.set_fact("khr_bool_eq", "type", "module")
      |> StateV2.set_fact("khr_bool_not", "type", "module")
      |> StateV2.set_fact("khr_bool_and", "type", "module")
      |> StateV2.set_fact("khr_bool_or", "type", "module")
      |> StateV2.set_fact("khr_bool_xor", "type", "module")

      # KHR Interactivity Nodes - Type Conversion
      |> StateV2.set_fact("khr_conv_bool_to_int", "type", "module")
      |> StateV2.set_fact("khr_conv_bool_to_float", "type", "module")
      |> StateV2.set_fact("khr_conv_int_to_bool", "type", "module")
      |> StateV2.set_fact("khr_conv_int_to_float", "type", "module")
      |> StateV2.set_fact("khr_conv_float_to_bool", "type", "module")
      |> StateV2.set_fact("khr_conv_float_to_int", "type", "module")

      # KHR Interactivity Nodes - Control Flow
      |> StateV2.set_fact("khr_flow_sequence", "type", "module")
      |> StateV2.set_fact("khr_flow_branch", "type", "module")
      |> StateV2.set_fact("khr_flow_switch", "type", "module")
      |> StateV2.set_fact("khr_flow_while", "type", "module")
      |> StateV2.set_fact("khr_flow_for", "type", "module")
      |> StateV2.set_fact("khr_flow_do_n", "type", "module")
      |> StateV2.set_fact("khr_flow_multi_gate", "type", "module")
      |> StateV2.set_fact("khr_flow_wait_all", "type", "module")
      |> StateV2.set_fact("khr_flow_throttle", "type", "module")
      |> StateV2.set_fact("khr_flow_set_delay", "type", "module")
      |> StateV2.set_fact("khr_flow_cancel_delay", "type", "module")

      # KHR Interactivity Nodes - State Manipulation
      |> StateV2.set_fact("khr_state_get", "type", "module")
      |> StateV2.set_fact("khr_state_set", "type", "module")
      |> StateV2.set_fact("khr_state_set_multiple", "type", "module")
      |> StateV2.set_fact("khr_state_interpolate", "type", "module")
      |> StateV2.set_fact("khr_state_pointer_get", "type", "module")
      |> StateV2.set_fact("khr_state_pointer_set", "type", "module")
      |> StateV2.set_fact("khr_state_pointer_interpolate", "type", "module")
      |> StateV2.set_fact("khr_state_animation_start", "type", "module")
      |> StateV2.set_fact("khr_state_animation_stop", "type", "module")
      |> StateV2.set_fact("khr_state_animation_stop_at", "type", "module")

      # KHR Interactivity Nodes - Event
      |> StateV2.set_fact("khr_event_on_start", "type", "module")
      |> StateV2.set_fact("khr_event_on_tick", "type", "module")
      |> StateV2.set_fact("khr_event_receive", "type", "module")
      |> StateV2.set_fact("khr_event_send", "type", "module")

      # KHR Interactivity Nodes - Debug
      |> StateV2.set_fact("khr_debug_log", "type", "module")

      # KHR Interactivity Dependencies
      |> StateV2.set_fact("khr_math_e", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_pi", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_infinity", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_nan", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_abs", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_sign", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_trunc", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_floor", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_ceil", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_round", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_fract", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_neg", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_add", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_sub", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_mul", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_div", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_rem", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_min", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_max", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_clamp", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_saturate", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_mix", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_eq", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_lt", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_le", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_gt", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_ge", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_is_nan", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_is_inf", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_select", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_switch", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_random", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_rad", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_deg", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_sin", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_cos", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_tan", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_asin", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_acos", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_atan", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_atan2", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_sinh", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_cosh", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_tanh", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_asinh", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_acosh", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_atanh", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_exp", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_log", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_log2", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_log10", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_sqrt", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_cbrt", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_pow", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_length", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_normalize", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_dot", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_cross", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_rotate2d", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_rotate3d", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_transform", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_transpose", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_determinant", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_inverse", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_matmul", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_matcompose", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_matdecompose", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_quat_conjugate", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_quat_mul", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_quat_angle_between", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_quat_from_axis_angle", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_quat_to_axis_angle", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_quat_from_directions", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_combine2", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_combine3", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_combine4", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_combine2x2", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_combine3x3", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_combine4x4", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_extract2", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_extract3", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_extract4", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_extract2x2", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_extract3x3", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_math_extract4x4", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_abs", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_sign", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_neg", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_add", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_sub", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_mul", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_div", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_rem", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_min", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_max", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_clamp", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_eq", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_lt", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_le", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_gt", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_ge", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_not", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_and", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_or", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_xor", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_asr", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_lsl", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_clz", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_ctz", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_int_popcnt", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_bool_eq", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_bool_not", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_bool_and", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_bool_or", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_bool_xor", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_conv_bool_to_int", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_conv_bool_to_float", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_conv_int_to_bool", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_conv_int_to_float", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_conv_float_to_bool", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_conv_float_to_int", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_sequence", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_branch", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_switch", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_while", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_for", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_do_n", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_multi_gate", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_wait_all", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_throttle", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_set_delay", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_flow_cancel_delay", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_get", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_set", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_set_multiple", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_interpolate", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_pointer_get", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_pointer_set", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_pointer_interpolate", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_state_animation_start", "depends_on", "gltf_animation")
      |> StateV2.set_fact("khr_state_animation_stop", "depends_on", "gltf_animation")
      |> StateV2.set_fact("khr_state_animation_stop_at", "depends_on", "gltf_animation")
      |> StateV2.set_fact("khr_event_on_start", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_event_on_tick", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_event_receive", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_event_send", "depends_on", "gltf_scene_graph")
      |> StateV2.set_fact("khr_debug_log", "depends_on", "gltf_scene_graph")


    todos = [
      {"develop_system", ["gltf"]}
    ]

    # Run the planner
    domain = AriaEngine.Domain.from_module(AriaEngine.SoftwareDevelopment.Domain)
    {:ok, plan} = Planning.plan(domain, initial_state, todos, verbose: 3)

    # For now, we'll just assert that a plan was found.
    # In a real scenario, we would inspect the plan to ensure it's optimal.
    assert is_list(plan)
    assert length(plan) > 0
  end
end
