# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

services:
  aria-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Phoenix app
      - "8200:8200"  # OpenBao
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - DATABASE_URL=postgresql://root@cockroachdb:26257/aria_character_core?sslmode=disable
      - VAULT_ADDR=http://localhost:8200
      - OPENBAO_PKCS11_PIN=${OPENBAO_PKCS11_PIN:-1234}
      - OPENBAO_PKCS11_SO_PIN=${OPENBAO_PKCS11_SO_PIN:-1234}
      - OPENBAO_PKCS11_SLOT=${OPENBAO_PKCS11_SLOT:-0}
      - RESET_HSM_KEYS=${RESET_HSM_KEYS:-true}
    volumes:
      - aria_data:/app/data
      - openbao_data:/vault/data
      - softhsm_tokens:/var/lib/softhsm/tokens
    depends_on:
      - cockroachdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health", "&&", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  cockroachdb:
    image: v-sekai/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure", "--host=localhost:26257"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  aria_data:
  openbao_data:
  softhsm_tokens:
  cockroachdb_data:
