# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install asdf and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
          echo ". ~/.asdf/asdf.sh" >> ~/.bashrc
          echo ". ~/.asdf/completions/asdf.bash" >> ~/.bashrc
          # Source asdf for the current session
          . ~/.asdf/asdf.sh

      - name: Install Erlang and Elixir
        run: |
          . ~/.asdf/asdf.sh
          asdf plugin add erlang || true # Add || true to prevent failure if plugin already exists
          asdf plugin add elixir || true
          asdf install erlang
          asdf install elixir
          asdf reshim erlang
          asdf reshim elixir