# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

name: Build and Test Aria Character Core

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or self-hosted runners if specific hardware/OS is needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies for asdf
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git build-essential # Add build-essential for Erlang compilation

      - name: Install asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
          echo ". ~/.asdf/asdf.sh" >> ~/.bashrc
          echo ". ~/.asdf/completions/asdf.bash" >> ~/.bashrc
          # Source asdf for the current session
          . ~/.asdf/asdf.sh

      - name: Install Erlang and Elixir (from .tool-versions)
        run: |
          . ~/.asdf/asdf.sh # Source asdf again for the current step
          asdf plugin add erlang || true
          asdf plugin add elixir || true
          asdf install erlang
          asdf install elixir
          asdf reshim erlang
          asdf reshim elixir

      - name: Install Elixir dependencies
        run: |
          . ~/.asdf/asdf.sh # Source asdf again
          mix deps.get
          mix deps.compile

      # --- External Service Installation (Example for CI) ---
      # These would be more complex, potentially using Docker or pre-built binaries

      - name: Install SeaweedFS
        run: |
          # Example: Download and extract binary
          wget -qO- https://github.com/seaweedfs/seaweedfs/releases/download/2.80/linux_amd64.tar.gz | tar xvz
          sudo cp weed /usr/local/bin/

      # --- Start Services for Integration Tests ---
      - name: Start External Services
        run: |
          # Create data directories
          mkdir -p seaweedfs-data/master seaweedfs-data/volume

          # Start SeaweedFS
          nohup weed master -mdir=./seaweedfs-data/master -defaultReplication=001 > seaweedfs_master.log 2>&1 &
          nohup weed volume -dir=./seaweedfs-data/volume -mserver="localhost:9333" > seaweedfs_volume.log 2>&1 &
          echo "Waiting for SeaweedFS..."
          timeout 30s bash -c 'until curl -sf http://localhost:9333/dir/status >/dev/null 2>&1; do sleep 2; done'

          echo "All external services started."

      - name: Run Elixir Unit Tests
        run: |
          . ~/.asdf/asdf.sh # Source asdf again
          mix test --exclude integration # Assuming you tag integration tests

      - name: Run Elixir Integration Tests
        run: |
          . ~/.asdf/asdf.sh # Source asdf again
          # Example: mix test --only integration
          # You might need to ensure your database is migrated for integration tests
          mix ecto.create # Create DB for tests
          mix ecto.migrate # Run migrations
          mix test --only integration # Run integration tests

      - name: Stop External Services
        if: always() # Run even if previous steps fail
        run: |
          pkill -f "weed" || true
          echo "External services stopped."