# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

name: Foundation Layer Startup (Local)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-start-foundation:
    name: Build and Start Foundation Layer Locally
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Install just
        run: |
          sudo apt-get install -y just

      - name: Start Foundation Layer Services using Docker Compose
        env:
          OPENBAO_PKCS11_PIN: ${{ secrets.OPENBAO_PKCS11_PIN }}
          OPENBAO_PKCS11_SO_PIN: ${{ secrets.OPENBAO_PKCS11_SO_PIN }}
          OPENBAO_PKCS11_SLOT: ${{ secrets.OPENBAO_PKCS11_SLOT }}
          GIT_SHA: ${{ github.sha }} # Or a fixed known good SHA for cockroachdb if preferred
        run: |
          just foundation-startup
