# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
# SPDX-License-Identifier: MIT

name: Layer Startup

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-start-foundation:
    name: Build and Start Foundation Layer Natively
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y just libncurses-dev libtinfo-dev autoconf cargo pkg-config
        
      - name: Install Erlang and Elixir
        run: |
          just install-elixir-erlang-env

      - name: Start Foundation Layer Services Natively
        env:
          OPENBAO_PKCS11_PIN: ${{ secrets.OPENBAO_PKCS11_PIN }}
          OPENBAO_PKCS11_SO_PIN: ${{ secrets.OPENBAO_PKCS11_SO_PIN }}
          OPENBAO_PKCS11_SLOT: ${{ secrets.OPENBAO_PKCS11_SLOT }}
        run: |
          just install-ubuntu-deps
          just install-cockroach
          just install-openbao
          just install-seaweedfs
          just start-foundation-core

      - name: Run Unit Tests
        run: |
          just test-unit-ci
